Projekt2/Models/ProjectModels/Holder.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Projekt2.Models.ProjectModels
{
    public class Holder
    {
        [MaxLength(40), MinLength(1), Required]
        public string Name { get; set; }
        public string UserId { get; set; }
        public Guid Id { get; set; }
        public List<Link> Links { get; set; }

        public Holder()
        {
            Id = Guid.NewGuid();
        }

        public Holder(string name, string userId)
        {
            Name = name;
            UserId = userId;
            Id = Guid.NewGuid();
            Links = new List<Link>();
        }

        public Holder(Guid id)
        {
            Id = id;
        }

        public override bool Equals(object obj)
        {
            if (obj is Holder holder)
            {
                return holder.Id.Equals(Id);
            }
            return false;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}

Projekt2/Controllers/HolderController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Projekt2.Models;
using Projekt2.Models.ProjectModels;

namespace Projekt2.Controllers
{
    
    public class HolderController : Controller
    {
        private readonly IHolderRepository _repository;

        private readonly UserManager<ApplicationUser> _user;

        public HolderController(IHolderRepository repository, UserManager<ApplicationUser> user)
        {
            _repository = repository;
            _user = user;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await _user.GetUserAsync(HttpContext.User);

            if (currentUser == null)
            {
                return RedirectToAction("NotLogged");
            }

            await RemoveHelp();
            var all = await _repository.GetAllHoldersAsync(currentUser.Id);
            var popular = await _repository.GetPopularLinksAsync();

            var vm = new IndexViewModel(all, popular);

            return View(vm);
        }
        [Authorize]
        public IActionResult AddHolder()
        {
            return View();
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> AddHolder(Holder holder)
        {
            if (ModelState.IsValid)
            {
                var user = await _user.GetUserAsync(HttpContext.User);
                holder.UserId = user.Id;

                await _repository.AddHolderAsync(holder);
                return RedirectToAction("Index");
            }

            return View(holder);
        }
        [Authorize]
        public IActionResult AddLink(Guid holderId)
        {
            var helpHolder = new Holder
            {
                Name = holderId.ToString(),
                UserId = "helper",
                Id = Guid.NewGuid()
            };
            _repository.AddHolderAsync(helpHolder);
            return View();
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> AddLink(Link link)
        {
            if (ModelState.IsValid)
            {
                var helpHolder =await  _repository.GetAllHoldersAsync("helper");
                var holder = helpHolder.First(h => h.UserId.Equals("helper"));

                if (link.Description == null)
                    link.Description = "-";

                await _repository.AddLinkAsync(link, Guid.Parse(holder.Name));
                await _repository.RemoveHolderAsync(holder.Id);

                return RedirectToAction("Index");
            }

            return View(link);
        }

        [Authorize]
        public async Task<IActionResult> RemoveHolder(Guid holderId)
        {
            await _repository.RemoveHolderAsync(holderId);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> RemoveLink(Guid linkId)
        {
            await _repository.RemoveLinkAsync(linkId);
            return RedirectToAction("Index");
        }

        [Authorize]
        public async Task<IActionResult> LinkInfo(Guid linkId)
        {
            var link = await _repository.GetLinkAsync(linkId);
            return View(link);
        }

        [Authorize]
        public async Task<IActionResult> Click(Guid linkId, string url)
        {
            await _repository.ClickAsync(linkId);
            return Redirect(url);
        }

        [Authorize]
        public async Task<IActionResult> Back()
        {
            await RemoveHelp();

            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult Error()
        {
            return View();
        }
        
        public IActionResult NotLogged()
        {
            return View();
        }

        [Authorize]
        public IActionResult Modify(Guid linkId)
        {
            var helpHolder = new Holder
            {
                Name = linkId.ToString(),
                UserId = "helper",
                Id = Guid.NewGuid()
            };
            _repository.AddHolderAsync(helpHolder);
            return View();
        }

        [HttpPost, Authorize]
        public async Task<IActionResult> Modify(Link link)
        {
            if (link.Name != null || link.Description != null)
            {
                var helpHolder = await _repository.GetAllHoldersAsync("helper");
                var holder = helpHolder.First(h => h.UserId.Equals("helper"));
                
                await _repository.ModifyLinkAsync(link, Guid.Parse(holder.Name));
                await _repository.RemoveHolderAsync(holder.Id);

                return RedirectToAction("Index");
            }

            return View(link);
        }

        [Authorize]
        public async Task<int> RemoveHelp()
        {
            var help = await _repository.GetAllHoldersAsync("helper");
            foreach (var holder in help)
            {
                await _repository.RemoveHolderAsync(holder.Id);
            }

            return 0;
        }
    }
}

Projekt2/Views/Holder/AddHolder.cshtml
@model Projekt2.Models.ProjectModels.Holder
@{
    ViewData["Title"] = "AddHolder";
}

<h2>Add Folder</h2>

<form asp-action="AddHolder" method="post">
    Name: &ensp;&nbsp;<input asp-for="Name"/> <span asp-validation-for="Name"></span> <br/>
    <input type="submit"/>
    <br/>
    <br/>
    <a class="btn btn-default" asp-controller="Holder" asp-action="Index">Go back</a>
</form>

Projekt2/Views/Holder/AddLink.cshtml
@model Projekt2.Models.ProjectModels.Link
@{
    ViewData["Title"] = "AddLink";
}

<h2>Add Link</h2>

<form asp-action="AddLink" method="post">
    <p>Name: &emsp;&ensp;&ensp;&ensp;&nbsp;<input asp-for="Name"/> <span asp-validation-for="Name"></span></p>
    <p>Url: &emsp;&emsp;&emsp;&ensp;&ensp;<input asp-for="Url"/> <span asp-validation-for="Url"></span></p>
    <p>Description: &nbsp;<input asp-for="Description"/> <span asp-validation-for="Description"></span></p>
    <input type="submit" />
    <br/>
    <br/>
    <a class="btn btn-default" asp-controller="Holder" asp-action="Back">Go back</a>
</form>

Projekt2/Views/Holder/Index.cshtml
@model Projekt2.Models.ProjectModels.IndexViewModel
@{
    ViewData["Title"] = "Index";
}

<head>
    <title>Home</title>
</head>

<h2>Home</h2>

@if(@Model.Holders.Capacity == 0) {
    <br/>
    <p>You have no folders.</p>
    <p><a asp-action="AddHolder">Click here</a> to add some right now.</p>
    <br/>
    <br/>
}
else {
    <a class="btn btn-success" asp-action="AddHolder"><i class="glyphicon glyphicon-plus"></i></a>
    <br/>
    <br/>
foreach (var holder in Model.Holders)
{
    
    <button class="btn btn-block btn-lg" onclick="hide(@Model.Holders.IndexOf(holder).ToString())">@holder.Name</button>
    <div id=@Model.Holders.IndexOf(holder).ToString()>
        <br />
        @foreach (var link in holder.Links)
        {
            <div class="container-fluid row">
                <a target="_blank" class="col-xs-4" asp-action="Click" asp-route-linkId="@link.Id" asp-route-url="@link.Url">@link.Name</a>
                <a style="color: darkred" class="col-xs-4" asp-controller="Holder" asp-action="RemoveLink" asp-route-holderId="@holder.Id" asp-route-linkId="@link.Id">Remove</a>
                <a class="col-xs-4 btn" asp-controller="Holder" asp-action="LinkInfo" asp-route-linkId="@link.Id"><i class="glyphicon glyphicon-info-sign"></i></a>
            </div>

        }
    </div>
    <br/>
    <a class="btn btn-info btn-sm" asp-action="AddLink" asp-route-holderId="@holder.Id">Add Link</a>
    <a class ="btn btn-danger btn-sm" asp-action="RemoveHolder" asp-route-holderId="@holder.Id"><i class="glyphicon glyphicon-trash"></i></a>
    <br/>
    <br/>
}
}
<br/>
<div class="row">
    <div class="col-xs-2">
        <p></p>
    </div>
    <div class="col-xs-5">
    <h4>Some popular links:</h4>
        <ol>
            @foreach (var link in Model.Popular)
            {
                <li> <a target="_blank" asp-action="Click" asp-route-linkId="@link.Id" asp-route-url="@link.Url">@link.Name</a> </li>
            }
        </ol>
   </div>
</div>
<script>
    function hide(id) {
        var x = document.getElementById(id);
        if (x.style.display === "none") {
            x.style.display = "block";
        } else {
            x.style.display = "none";
        }
    }
</script>

Projekt2/Views/Holder/LinkInfo.cshtml
@model Projekt2.Models.ProjectModels.Link

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<h2>Info</h2>
<p>Name: @Model.Name</p>
<p>Description: @Model.Description</p>
<p>Times clicked: @Model.Clicked</p>
<p>URL: <a target="_blank" asp-action="Click" asp-route-linkId="@Model.Id" asp-route-url="@Model.Url">@Model.Url</a></p>
<br/>
<div class="row container-fluid">
    <a class="btn btn-danger" asp-action="RemoveLink" asp-route-linkId="@Model.Id">Remove</a>
    <a class="btn btn-info" asp-action="Modify" asp-route-linkId="@Model.Id"><i class="glyphicon glyphicon-cog"></i></a>
    <a class="btn btn-default" asp-action="Index">Go back</a>
</div>

Projekt2/Views/Holder/Modify.cshtml
@model Projekt2.Models.ProjectModels.Link
@{
    ViewData["Title"] = "AddLink";
}
<h2>Modify link</h2>
<form asp-action="Modify" method="post">
    <p>Name: &emsp;&ensp;&ensp;&ensp;&nbsp;<input asp-for="Name" /> <span asp-validation-for="Name"></span></p>
    <p>Description: &nbsp;<input asp-for="Description" /> <span asp-validation-for="Description"></span></p>
    <input type="submit" />
    <br />
    <br />
    <a class="btn btn-default" asp-controller="Holder" asp-action="Back">Go back</a>
</form>

Projekt2/Views/Holder/NotLogged.cshtml
@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<style>
    body {
        margin-top: 100px;
    }
</style>
<head>
    <title>NotLoggedIn</title>
</head>

<h2>You need to be logged in to use this application.</h2>
<h3><a href="/Account/Register">Click here</a> to register or <a href="/Account/Login">here</a> to log in.</h3>